// Mattermost stores a reaction by name ("white_check_mark"); the chat stores the character itself.
// The names seen in the Rowan Rose Mattermost, plus the common ones. Unknown names are left out.
const NAMES = {
  white_check_mark: '✅',
  '+1': '👍',
  thumbsup: '👍',
  '-1': '👎',
  thumbsdown: '👎',
  heart: '❤️',
  hearts: '💕',
  two_hearts: '💕',
  revolving_hearts: '💞',
  heartpulse: '💗',
  heartbeat: '💓',
  heart_eyes: '😍',
  kissing_heart: '😘',
  kissing_closed_eyes: '😚',
  smiling_face_with_3_hearts: '🥰',
  smiling_face_with_tear: '🥲',
  bomb: '💣',
  boom: '💥',
  partying_face: '🥳',
  raised_hands: '🙌',
  clap: '👏',
  fire: '🔥',
  dancer: '💃',
  man_dancing: '🕺',
  heavy_plus_sign: '➕',
  dizzy: '💫',
  comet: '☄️',
  firecracker: '🧨',
  joy: '😂',
  rolling_on_the_floor_laughing: '🤣',
  airplane: '✈️',
  pray: '🙏',
  balloon: '🎈',
  negative_squared_cross_mark: '❎',
  x: '❌',
  rose: '🌹',
  clinking_glasses: '🥂',
  100: '💯',
  cherry_blossom: '🌸',
  sunflower: '🌻',
  sweat_smile: '😅',
  wave: '👋',
  ok_hand: '👌',
  grinning: '😀',
  grin: '😁',
  smile: '😄',
  innocent: '😇',
  sunglasses: '😎',
  facepunch: '👊',
  warning: '⚠️',
  money_mouth_face: '🤑',
  money_with_wings: '💸',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  tada: '🎉',
  hamster: '🐹',
  see_no_evil: '🙈',
  hear_no_evil: '🙉',
  expressionless: '😑',
  neutral_face: '😐',
  call_me_hand: '🤙',
  hand: '✋',
  'man-gesturing-ok': '🙆‍♂️',
  'woman-with-bunny-ears-partying': '👯‍♀️',
  'woman-shrugging': '🤷‍♀️',
  'man-shrugging': '🤷‍♂️',
  'man-running': '🏃‍♂️',
  cry: '😢',
  pensive: '😔',
  persevere: '😣',
  grimacing: '😬',
  blush: '😊',
  yum: '😋',
  'star-struck': '🤩',
  shushing_face: '🤫',
  hugging_face: '🤗',
  rocket: '🚀',
  sparkles: '✨',
  tophat: '🎩',
  tumbler_glass: '🥃',
  white_heart: '🤍',
  eyes: '👀',
  thinking_face: '🤔',
  muscle: '💪',
  star: '⭐',
  rotating_light: '🚨',
  bell: '🔔',
  bulb: '💡',
  checkered_flag: '🏁',
  trophy: '🏆',
  coffee: '☕',
  laughing: '😆',
  wink: '😉',
  sob: '😭',
  rage: '😡',
  scream: '😱',
  flushed: '😳',
  point_up: '☝️',
  point_right: '👉',
  handshake: '🤝',
  heavy_check_mark: '✔️',
  question: '❓',
  exclamation: '❗',
};

/** The emoji for a Mattermost reaction name, or null when it is not known. Skin-tone suffixes are dropped. */
export function emojiOf(name) {
  if (typeof name !== 'string') return null;
  const plain = name.replace(/_skin-tone-\d$/, '').replace(/::skin-tone-\d$/, '');
  return NAMES[plain] || null;
}
